baseURL = 'https://rafffle.github.io'
languageCode = 'en-us'
title = 'raphael esquivel'

theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "â†©"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[menu]

  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    name="CV"
    url="/CV/english.pdf"
    weight=2
  [[menu.main]]
    name = "Talks"
    url = "talks/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "proj/"
    weight = 4

  [[menu.main]]
    name = "Bookshelf"
    url="books/"
    weight=5

[params]
  description = "A website built through Hugo and blogdown."
  footer = "Email: [esquivelralphie@gmail.com](esquivelralphie@gmail.com) | [Github](https://github.com/rafffle) | [LinkedIn](https://www.linkedin.com/in/raphael-rm-esquivel/)"


[markup]

  [markup.goldmark]

    [markup.goldmark.renderer]
      unsafe = true